name: "Dashboard"
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '0 13 * * *'
  push:
    branches:
      - main
      - master

jobs:
  update-data:
    name: Update Dashboard
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Add Quarto to PATH
        run: |
          echo "export PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
      - run: |
          quarto --version
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libudunits2-dev \
          libgdal-dev
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: "Install Packages"
        run: |
          install.packages('httr')
          install.packages('remotes')
          remotes::install_github('hadley/emo')
          install.packages('shiny')
          install.packages('scales')
          install.packages('treemap')
          install.packages('htmltools')
          install.packages('here')
          install.packages('jsonlite')
          install.packages('janitor')
          install.packages('quarto')
          install.packages('tidyverse')
          install.packages('highcharter')
          install.packages('openxlsx')
          install.packages('lubridate')
          install.packages('gt')
          install.packages('gtExtras')
          install.packages('httr2')
        shell: Rscript {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          needs: |
            any::tidyverse
            any::httr
            any::remotes
            any::shiny
            any::scales
            any::treemap
            any::here
            any::jsonlite
            any::janitor
            any::quarto
            any::highcharter
            any::lubridate
            any::gt
            any::gtExtras
            any::pacman
            any::openxlsx
            any::sf
            any::xml2
            any::rvest
            any::reticulate
            any::fs
            any::countrycode
            any::progress
            any::cli
            any::digest
            any::glue
            any::vroom
            any::prettydoc
            any::DT
            any::piggyback
            any::httr2
            any::openssl
            any::priceR
      - name: "Script - Update Dashboard"
        run: Rscript 'start.R'
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Script Routine Seven
